import bg20 from "/public/assets/img/bg20.jpg";
import bg23 from "/public/assets/img/bg23.png";
import bg25 from "/public/assets/img/bg25.jpg";
import bg26 from "/public/assets/img/bg26.jpg";

const sourcesPerPage = 4;

const listSource = [
  {
    id: 0,
    title: "Bộ Lạc Thần Thú H5 – Source Game H5 Chuẩn Thương Mại",
    subtitle: "",
    type: "GAME H5",
    date: "date",
    image: bg20,
    link: "#",
    price: 4560000,
    discount: 20,
  },
  {
    id: 1,
    title: "3Q Mobile – Server Game Mobile Đầy Đủ Android/IOS",
    subtitle: "",
    type: "GAME MOBILE",
    date: "date",
    image: bg23,
    link: "#",
    price: 8790000,
    discount: 18,
  },
  {
    id: 2,
    title: "Đấu Trường Hải Tặc – Source Game Thương Mại Đông Người Chơi",
    subtitle: "",
    type: "GAME PC",
    date: "date",
    image: bg25,
    link: "#",
    price: 3220000,
    discount: 15,
  },
  {
    id: 3,
    title: "MU H5 2023 – Source Game Bản Thương Mại Mới Nhất",
    subtitle: "",
    type: "GAME H5",
    date: "date",
    image: bg26,
    link: "#",
    price: 7630000,
    discount: 17,
  },
  {
    id: 4,
    title: "Bộ Lạc Thần Thú H5 – Source Game H5 Chuẩn Thương Mại",
    subtitle: "",
    type: "GAME H5",
    date: "date",
    image: bg20,
    link: "#",
    price: 4990000,
    discount: 16,
  },
  {
    id: 5,
    title: "3Q Mobile – Server Game Mobile Đầy Đủ Android/IOS",
    subtitle: "",
    type: "GAME MOBILE",
    date: "date",
    image: bg23,
    link: "#",
    price: 2760000,
    discount: 15,
  },
  {
    id: 6,
    title: "Đấu Trường Hải Tặc – Source Game Thương Mại Đông Người Chơi",
    subtitle: "",
    type: "GAME PC",
    date: "date",
    image: bg25,
    link: "#",
    price: 6200000,
    discount: 19,
  },
  {
    id: 7,
    title: "MU H5 2023 – Source Game Bản Thương Mại Mới Nhất",
    subtitle: "",
    type: "GAME H5",
    date: "date",
    image: bg26,
    link: "#",
    price: 7850000,
    discount: 15,
  },
  {
    id: 8,
    title: "Bộ Lạc Thần Thú H5 – Source Game H5 Chuẩn Thương Mại",
    subtitle: "",
    type: "GAME H5",
    date: "date",
    image: bg20,
    link: "#",
    price: 3650000,
    discount: 20,
  },
  {
    id: 9,
    title: "3Q Mobile – Server Game Mobile Đầy Đủ Android/IOS",
    subtitle: "",
    type: "GAME MOBILE",
    date: "date",
    image: bg23,
    link: "#",
    price: 4120000,
    discount: 17,
  },
  {
    id: 10,
    title: "Đấu Trường Hải Tặc – Source Game Thương Mại Đông Người Chơi",
    subtitle: "",
    type: "GAME PC",
    date: "date",
    image: bg25,
    link: "#",
    price: 8450000,
    discount: 18,
  },
  {
    id: 11,
    title: "MU H5 2023 – Source Game Bản Thương Mại Mới Nhất",
    subtitle: "",
    type: "GAME H5",
    date: "date",
    image: bg26,
    link: "#",
    price: 5290000,
    discount: 20,
  },
  {
    id: 12,
    title: "Bộ Lạc Thần Thú H5 – Source Game H5 Chuẩn Thương Mại",
    subtitle: "",
    type: "GAME H5",
    date: "date",
    image: bg20,
    link: "#",
    price: 9900000,
    discount: 16,
  },
  {
    id: 13,
    title: "3Q Mobile – Server Game Mobile Đầy Đủ Android/IOS",
    subtitle: "",
    type: "GAME MOBILE",
    date: "date",
    image: bg23,
    link: "#",
    price: 2220000,
    discount: 20,
  },
  {
    id: 14,
    title: "Đấu Trường Hải Tặc – Source Game Thương Mại Đông Người Chơi",
    subtitle: "",
    type: "GAME PC",
    date: "date",
    image: bg25,
    link: "#",
    price: 4860000,
    discount: 15,
  },
  {
    id: 15,
    title: "MU H5 2023 – Source Game Bản Thương Mại Mới Nhất",
    subtitle: "",
    type: "GAME H5",
    date: "date",
    image: bg26,
    link: "#",
    price: 6150000,
    discount: 17,
  },
  {
    id: 16,
    title: "Bộ Lạc Thần Thú H5 – Source Game H5 Chuẩn Thương Mại",
    subtitle: "",
    type: "GAME H5",
    date: "date",
    image: bg20,
    link: "#",
    price: 2790000,
    discount: 19,
  },
  {
    id: 17,
    title: "3Q Mobile – Server Game Mobile Đầy Đủ Android/IOS",
    subtitle: "",
    type: "GAME MOBILE",
    date: "date",
    image: bg23,
    link: "#",
    price: 7540000,
    discount: 15,
  },
  {
    id: 18,
    title: "Đấu Trường Hải Tặc – Source Game Thương Mại Đông Người Chơi",
    subtitle: "",
    type: "GAME PC",
    date: "date",
    image: bg25,
    link: "#",
    price: 6110000,
    discount: 18,
  },
  {
    id: 19,
    title: "MU H5 2023 – Source Game Bản Thương Mại Mới Nhất",
    subtitle: "",
    type: "GAME H5",
    date: "date",
    image: bg26,
    link: "#",
    price: 9980000,
    discount: 16,
  },
  {
    id: 20,
    title: "Bộ Lạc Thần Thú H5 – Source Game H5 Chuẩn Thương Mại",
    subtitle: "",
    type: "GAME H5",
    date: "date",
    image: bg20,
    link: "#",
    price: 3450000,
    discount: 15,
  },
];

export { listSource, sourcesPerPage };
